# Generated by Django 3.2 on 2022-09-05 19:11

from django.db import migrations, models
import uploadedfiles.s3_storage


class Migration(migrations.Migration):

    dependencies = [
        ('uploadedfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='fname',
            field=models.FileField(max_length=512, storage=uploadedfiles.s3_storage.PublicMediaStorage(), unique=True, upload_to=''),
        ),
    ]
