# Generated by Django 3.2 on 2022-09-18 23:36

from django.db import migrations, models
import uploadedfiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadedfiles', '0003_alter_uploadedfile_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='fname',
            field=models.FileField(max_length=512, unique=True, upload_to=uploadedfiles.models.uploaded_file_path),
        ),
    ]
